ALTER TABLE people ADD COLUMN IF NOT EXISTS street VARCHAR(255);
ALTER TABLE people ADD COLUMN IF NOT EXISTS number VARCHAR(50);
ALTER TABLE people ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(255);
ALTER TABLE people ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE people ADD COLUMN IF NOT EXISTS state VARCHAR(50);
ALTER TABLE people ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
